name: Deploy To DigitalOcean

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v2
      # Copy files to droplet
      - name: Deploy to DO
        run: |
          which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )
          which rsync || ( apt-get update -y && apt-get install rsync -y )
          eval $(ssh-agent -s)
          ssh-add <(echo "$SSH_PRIVATE_KEY" )
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          scp -r * root@$SERVER_IP:/var/www/html/wp-content/themes/m99
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      CI: false
